### ISSUE TITLE
診療時間

### ISSUE THREAD

**Issue by zimuya** [KatsuyaHiguchi-colabPlanet/itonooka-hospital#1]
・診療時間ですが、第二土曜日のみ、土曜日は休診です。

**Comment by KatsuyaHiguchi-colabPlanet** [comment]
@zimuya 
こちら対応し、デプロイが完了致しました。

**Comment by zimuya** [comment]
@KatsuyaHiguchi-colabPlanet 
金曜午後に＊ではなく、第二土曜に＊ではないですか？

「第二土曜日のみ外来受付」として、「土曜日は休診です」は削除
表の中の日曜列も削除してください。

**Comment by zimuya** [comment]
@KatsuyaHiguchi-colabPlanet 
http://www.itonooka.dr-clinic.jp/
を見たところ、逆ですね。
「第二土曜日のみ休診、それ以外は土曜日も外来受付」です。
