### ISSUE TITLE
index　初診予約制導入をレスポンシブに

### ISSUE THREAD

**Issue by KatsuyaHiguchi-colabPlanet** [KatsuyaHiguchi-colabPlanet/itonooka-hospital#31]
開閉アイコンも設置

**Comment by zimuya** [comment]
- [ ] 最後に読点が２つある
- [ ] 読みにくい

**Comment by zimuya** [comment]
開閉のタップ範囲がシビアすぎます。住所電話も初期非表示枠に移しても良いので、border内はどこをタップしても開閉できるようにしてください。

**Comment by zimuya** [comment]
一応意図通りになっていますが、aタグの中にhとdivいれるのではだめだったのでしょうか？

**Comment by KatsuyaHiguchi-colabPlanet** [comment]
aタグでdivかこえたんですね、ブロック要素はかこえないものだと思ってました・・・。

それはそれとして、頂いた方法ですとlgサイズで開閉機能を使いたくない場合にOFFにできないのではと思います。

**Comment by zimuya** [comment]
html、cssは過去の知識は捨てたほうが正しい情報を得られます。
ちゃんと調べましょう。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/div

lg時にpe-noneで大丈夫だと思うけど、pe-lg-noneとかがないのかな…？
確かにbootstrapセレクタだけでやろうとすると現状になるかもです。
ただ、pe-noneのほうが可読性は高いですね。
私だったら、事前にlgとかに対応したpointer-events: none;の独自セレクタを準備するかなと。

**Comment by zimuya** [comment]
まった、電話番号がありましたね。樋口さんの方法が正しいです。
一方で、電話番号リンクが機能していないです。position指定がうまく行ってない？

**Comment by zimuya** [comment]
positionが理解できていないのでは？電話番号リンクかその親などにposition-relativeを当ててみてください。
