### ISSUE TITLE
indexレイアウト調整

### ISSUE THREAD

**Issue by KatsuyaHiguchi-colabPlanet** [KatsuyaHiguchi-colabPlanet/itonooka-hospital#32]
- [x] サイドバーをもう少し上に
- [x] mainはjumbotronと重複しないように
- [x] 診療案内の「詳細はこちら」をボタン状に
- [x] 本文にline-heigtが効いていない
- [x] mdサイズのナビゲーション配置を変更
- [x] main箇所左のbg-img対応

スマホ版
- [x] お知らせのタイトルフォントをもう少し小さく
- [x] ヘッダの「・・・」アイコンとコンテンツの幅を調整
- [x] ヘッダの住所・電話番号フォントを小さく、立幅も狭く調整
- [x] ヘッダの病院ロゴを大きく

**Comment by zimuya** [comment]
main箇所左側のbg-imgも。（緑の蔦）

**Comment by zimuya** [comment]
mainのbg-imgがスマホとPCで違うのってなんでですか？
あと、jumbotornとfooterと接続してください。（bg-imgとの間に余白は不要）

**Comment by KatsuyaHiguchi-colabPlanet** [comment]
mainのbg-imgについては、スマホ版ですと大きく文字に被ってくるので、少し薄めのほうが視認性が良くなるとの判断です。

mdサイズのナビゲーションについては配置に難航しています。
横幅768（mdサイズの最小）のときなどに現状だとメニューがかなり改行されてしまうので、できればメニューを一段下げて表示幅を確保したいのですが・・・。

**Comment by zimuya** [comment]
意図は了解しましたし、今回はこれでいいですが、opacity使ったりmax-widthとかをレスポンシブでやると思います。

はい、md時のnavはbannerの下で良いと思います

**Comment by zimuya** [comment]
md時のaddressブロックは、navのすぐ上にしてください（下寄せ）

**Comment by zimuya** [comment]
今度はロゴ位置がおかしくなっています
![image](https://github.com/KatsuyaHiguchi-colabPlanet/itonooka-hospital/assets/80227551/7ef54035-676b-4da3-b282-4e0e3f418c9d)

**Comment by zimuya** [comment]
最上部の無駄な余白はなくしてください
