### ISSUE TITLE
各ページ h3の改行対応

### ISSUE THREAD

**Issue by KatsuyaHiguchi-colabPlanet** [KatsuyaHiguchi-colabPlanet/itonooka-hospital#41]
h3タグの内容が長いと改行が入り、左右アイコンも相まって見栄えが悪い
例：病院理念 - わかりやすく納得のいく医療を誠実に提供いたします。

案１：左右アイコンを無くし、下部アイコンとする
案２：表題を別の短い文章に変更し、長いものは1つ下にh4タグで設定する
案３：改行する長さの場合、アイコンは画面左・右端、縦位置中央寄せになるよう修正する

**Comment by KatsuyaHiguchi-colabPlanet** [comment]
案１：デザイン的にバランスのとれるアイコン選定に時間がかかる
案３：見栄えに違和感がありそう
より、案２を採用します。

**Comment by zimuya** [comment]
h3とh4に分割するのはありですが、
h3から削除して、h4にも出てこないのはナシです。先方へ確認が必須です。

**Comment by KatsuyaHiguchi-colabPlanet** [comment]
teamsで頂いた通り、提案書として変更案を作成致します。

**Comment by zimuya** [comment]
別issueで建ててください
